# Generated by Django 4.2.1 on 2023-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="mobile",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="secondary_mobile",
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="requestforconnectwithus",
            name="registered_mobile",
            field=models.BigIntegerField(unique=True),
        ),
    ]
