# Generated by Django 4.2.1 on 2023-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_address_mobile_alter_address_secondary_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="secondary_mobile",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
