# Generated by Django 4.2.1 on 2023-06-02 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_address_secondary_mobile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CartItems",
        ),
    ]
