# Generated by Django 4.2.1 on 2023-05-29 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_user_is_admin_user_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="is_admin",
        ),
    ]
