# Generated by Django 4.2.1 on 2023-05-29 17:50

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_is_staff_user_is_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brandName", models.CharField(max_length=30, unique=True)),
                ("brandDiscription", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=30, unique=True)),
                ("categoryDiscription", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "product_image1",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.image_upload_path
                    ),
                ),
                (
                    "product_image2",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.image_upload_path
                    ),
                ),
                (
                    "product_image3",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.image_upload_path
                    ),
                ),
                (
                    "product_image4",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.image_upload_path
                    ),
                ),
                (
                    "product_image5",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.image_upload_path
                    ),
                ),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("dicription", models.CharField(max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                ("product_created", models.DateTimeField(auto_now_add=True)),
                ("product_updated", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.brandname"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
        ),
    ]
