# Generated by Django 4.2.1 on 2023-06-04 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_id",
            field=models.ManyToManyField(to="core.productconfiguration"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="CartItems",
        ),
    ]
