# Generated by Django 4.2.1 on 2023-05-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_delete_userttype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandname",
            name="brandDiscription",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="categoryDiscription",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="dicription",
            field=models.TextField(max_length=255),
        ),
    ]
