# Generated by Django 4.2.1 on 2023-06-04 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_cart_product_id_alter_cart_user_delete_cartitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
        migrations.RemoveField(
            model_name="requestforconnectwithus",
            name="register_country",
        ),
        migrations.RemoveField(
            model_name="state",
            name="country",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
