# Generated by Django 4.2.1 on 2023-05-29 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_brandname_branddiscription_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brandname",
            old_name="brandDiscription",
            new_name="brand_discription",
        ),
        migrations.RenameField(
            model_name="brandname",
            old_name="brandName",
            new_name="brand_name",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="categoryDiscription",
            new_name="category_discription",
        ),
    ]
